apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
#    app.kubernetes.io/name: spring-sensors
    app.tanzu.vmware.com/workload-type: web
#   app.kubernetes.io/part-of: spring-sensors
#    apps.tanzu.vmware.com/has-tests: true 
spec:
  source:
    git:
      # update when code is pushed to a new location
      url: https://github.com/jdarrellvmware/spring-sensors.git
      ref:
        branch: main
  env:
  - name: TESTVAR
    value: aoeu
